### ISSUE TITLE
javadoc is necessary to build the doc, even if we don't build java

### ISSUE THREAD

**Issue by mquinson** [mquinson/simgrid#10]
Hello,

when building the documentation, (cmake -Denable_documentation=true), javadoc is mandatory even if java is not enabled (-Denable_java=false). In that case, if javadoc is not to be found the compilation process fails and stops.

We should test for javadoc (and use it) only if java is enabled.

**Comment by ptitpoulpe** [comment]
Coucou mon ptit martin, ça va ? 

vous arrivez pas à corriger ça ? 

Le 02.06.2015 16:06, Martin Quinson a écrit : 

> Hello, 
> 
> when building the documentation, (cmake -Denable_documentation=true), javadoc is mandatory even if java is not enabled (-Denable_java=false). In that case, if javadoc is not to be found the compilation process fails and stops. 
> 
> We should test for javadoc (and use it) only if java is enabled. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/mquinson/simgrid/issues/10
