### ISSUE TITLE
We need a new context factory for Mac OSX

### ISSUE THREAD

**Issue by mquinson** [mquinson/simgrid#11]
The support for swapcontext was removed from OSX 10.9 by Apple, so simgrid is unable to compile out of the box on these machines (this function was removed from posix 2008).

We could try to change the cmake stuff to pick the raw assembly contexts on Mac too (these are amd64 processors after all).

We could devise a new factory based on [Boost.Context](http://www.boost.org/doc/libs/1_57_0/libs/context/doc/html/). Boost would be better than us at maintaining our portability layer.

See also https://lists.gforge.inria.fr/pipermail/simgrid-user/2015-June/003708.html

**Comment by randomstuff** [comment]
* Currently works only for Boost <= 1.55 (the Boost.Context API changed slightly afterwards).
    
* Does not work with MC because we currently depend on the contexts being ucontext_t (we'd have to convert fcontext into ucontext_t).
    
* No support for parallel execution support (yet).

**Comment by randomstuff** [comment]
* Add support for newer version of boost.

* Add support for parallel execution.

* In fact ucontext *is* in OS X 10.9 (even if I did not find if in the Darwin source code) (but deprecated).
