### ISSUE TITLE
The backbone term in the cluster tag is misnamed

### ISSUE THREAD

**Issue by alegrand** [mquinson/simgrid#13]
In the documentation http://simgrid.gforge.inria.fr/simgrid/3.12/doc/platform.html#pf_cluster, Laurent Pouilloux reported that the backbone term is misleading. The right term is rather backplane. We could change the documentation and/or also the bb_* names.

**Comment by mquinson** [comment]
At the very least, we should make sure that the lua interface get it right and use backplane.

**Comment by Shurakai** [comment]
I added this to my personal todo list as I will take care of the Lua issue; didn't see this report before, sorry.

**Comment by mquinson** [comment]
After investigating, it seems that backbone is well name: that's the SHARED network in the middle of the cluster.
The backplane would be the limiter_link of the cluster. Problem: that limiter_link is not documented. We should use that doc, probably: ```Bandwidth for limiter link (if any). This adds a specific link for each node, to set the maximum bandwidth reached when communicating in both directions at the same time. In theory this value should be 2*bw for fullduplex links, but this might be less. The value heavily depends on the communication model,and on the cluster's hardware, so no default value can be set. This has to be measured. See the SMPI-101 tutorial for more information.```

**Comment by mquinson** [comment]
Actually, this is fixed in 8704bd70e399d9254c97a1b082bc874db2a0a97e so, I'm closing the bug.
@lpouillo would you say that it's OK now?

**Comment by lpouillo** [comment]
yes :)
