### ISSUE TITLE
Energy is unimplemented for model ptask_L07

### ISSUE THREAD

**Issue by mpoquet** [mquinson/simgrid#27]
Hello,

I would like to use the energy plugin of SimGrid but it looks ilke it is not implemented for the ptask_L07 model  at the moment. Do you plan to implement it soon ? It is more a feature request than an issue but I did not know where it should be put...

ptask_L07 energy hello world:
```C
#include <stdio.h>
#include <simgrid/msg.h>
#include <simgrid/plugins.h>

int main(int argc, char ** argv)
{
    sg_energy_plugin_init();
    MSG_init(&argc, argv);

    // Without the following line, everything works
    MSG_config("host/model", "ptask_L07");

    const char * platform_filename = argv[1];
    MSG_create_environment(platform_filename);

    xbt_dynar_t all_hosts = MSG_hosts_as_dynar();
    msg_host_t host;
    unsigned int i;

    xbt_dynar_foreach(all_hosts, i, host)
    {
        printf("Host %s has %d pstates\n",
            MSG_host_get_name(host),
            MSG_host_get_nb_pstates(host));
    }

    msg_error_t err = MSG_main();

    if (err == MSG_OK)
    	printf("Okay.\n");
    else
    	printf("Oops!\n");

    return 0;
}
```

Execution with energy_platform.xml as parameter:
```
[0.000000] [surf_host/INFO] Switching to the L07 model to handle parallel tasks.
** SimGrid: UNCAUGHT EXCEPTION received on ./a.out(0): category: unknown error; value: 0
** Function getNbPstates unimplemented
** Thrown by () in this process
[0.000000] /home/carni/proj/simgrid-dev/src/xbt/ex.c:148: [xbt_ex/CRITICAL] Function getNbPstates unimplemented

**   In _ZN6CpuL0712getNbPstatesEv() at /home/carni/proj/simgrid-dev/src/surf/host_ptask_L07.hpp:124
**   In SIMIX_simcall_handle() at /home/carni/proj/simgrid-dev/src/simix/popping_generated.c:375
**   In simcall_BODY_host_get_nb_pstates() at /home/carni/proj/simgrid-dev/src/simix/popping_bodies.c:268
**   In main() at /home/carni/proj/test/simgrid_bug/unimplemented.c:21 (discriminator 3)
```

Execution with energy_platform.xml as parameter (but without the "host/model" being overwritten):
```
Host MyHost1 has 3 pstates
Host MyHost2 has 1 pstates
Okay.
[0.000000] [surf_energy/INFO] Total energy of host MyHost1: 0.000000 Joules
[0.000000] [surf_energy/INFO] Total energy of host MyHost2: 0.000000 Joules
```

**Comment by randomstuff** [comment]
Would it make sense to move the energy logic to the base class (`Cpu`) ?

**Comment by mquinson** [comment]
@randomstuff exactly, that's the way to go, I'd say. It presents some disadvantages (such as the functionality bloat in the root class), but it is overcomed  by the advantages.

**Comment by mpoquet** [comment]
When do you think that this feature will be implemented ? We would like to do energy-oriented experiments soon but we can't without it :(. If you don't have the time to do it, I can try to implement it myself (if you tell me roughly how to). Thanks!

**Comment by mquinson** [comment]
Soon. I tried to move the energy from the CpuCas01 to the Cpu common ancestor, and it broke a bit. But I know the fix, I just need some time to implement this.

**Comment by mquinson** [comment]
@randomstuff could you please implement the trick of having an separate method to emit the host destruction callback, and call it in the destructor of child classes, please? 

Then, moving the pstates up from CpuCas01 to Cpu should be easy (if nothing else breaks on that way)
