### ISSUE TITLE
MSG (ptask_L07) : segmentation fault on communication between processes

### ISSUE THREAD

**Issue by mpoquet** [mquinson/simgrid#28]
Hello,

My simulator doesn't work since commit eae2ca68. I tried to create a MWE and I finally got one, which is below. Has the way to communicate between processes changed with this commit?

MWE:
```C
#include <stdio.h>

#include <simgrid/msg.h>

XBT_LOG_NEW_DEFAULT_CATEGORY(mwe, "mwe");

void send_message(const char *dst, void *data)
{
    msg_task_t task_sent = MSG_task_create(NULL, 0, 1e-6, data);
    XBT_INFO("message from '%s' to '%s'", MSG_process_get_name(MSG_process_self()), dst);
    MSG_task_send(task_sent, dst);
}

int submitter(int argc, char ** argv)
{
    send_message("server", NULL);
    // ...
    return 0;
}

int server(int argc, char ** argv)
{
    msg_task_t task_received = NULL;
    MSG_task_receive(&task_received, "server");
    void * data = MSG_task_get_data(task_received);
    // ...
    MSG_task_destroy(task_received);
    return 0;
}


int main(int argc, char ** argv)
{
    MSG_init(&argc, argv);
    MSG_config("host/model", "ptask_L07");

    const char * platform_filename = argv[1];
    MSG_create_environment(platform_filename);

    msg_host_t master_host = MSG_get_host_by_name("Jupiter");

    MSG_process_create("submitter", submitter, NULL, master_host);
    MSG_process_create("server", server, NULL, master_host);

    msg_error_t err = MSG_main();

    if (err == MSG_OK)
    	printf("Okay.\n");
    else
    	printf("Oops!\n");

    return 0;
}
```
Execution on commit 2b7c35f96 and before:
```
[0.000000] [surf_host/INFO] Switching to the L07 model to handle parallel tasks.
[Jupiter:submitter:(1) 0.000000] [mwe/INFO] message from 'submitter' to 'server'
Okay.
```
Execution on commit eae2ca6 and after:
```
[0.000000] [surf_host/INFO] Switching to the L07 model to handle parallel tasks.
[Jupiter:submitter:(1) 0.000000] [mwe/INFO] message from 'submitter' to 'server'
Segmentation fault.
Erreur de segmentation (core dumped)
```

**Comment by frs69wq** [comment]
The problem only happens with the ptask_l07 model (works fine with default compound).
With the stable 3.12 version, valgrind says:

==21472== Use of uninitialised value of size 8
==21472==    at 0x4EF9180: NetworkL07Model::communicate(RoutingEdge*, RoutingEdge*, double, double) (host_ptask_L07.cpp:301)
==21472==    by 0x4F72966: SIMIX_comm_irecv (smx_network.c:723)
==21472==    by 0x500944C: simcall_HANDLER_comm_recv (smx_network.c:426)
==21472==    by 0x509784A: SIMIX_simcall_handle (popping_generated.c:542)
==21472==    by 0x50BEE89: SIMIX_run (smx_global.c:442)
==21472==    by 0x50C0406: MSG_main (msg_global.c:126)
==21472==    by 0x400EAC: main (toto.c:47)
==21472== 
==21472== Invalid read of size 8
==21472==    at 0x4EF9180: NetworkL07Model::communicate(RoutingEdge*, RoutingEdge*, double, double) (host_ptask_L07.cpp:301)
==21472==    by 0x4F72966: SIMIX_comm_irecv (smx_network.c:723)
==21472==    by 0x500944C: simcall_HANDLER_comm_recv (smx_network.c:426)
==21472==    by 0x509784A: SIMIX_simcall_handle (popping_generated.c:542)
==21472==    by 0x50BEE89: SIMIX_run (smx_global.c:442)
==21472==    by 0x50C0406: MSG_main (msg_global.c:126)
==21472==    by 0x400EAC: main (toto.c:47)
==21472==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==21472== 

Problem is, both arrays needed by the ptask are well allocated in the function (with xbt_new0)

Eliminated suspects: ptask with same host on both sides, message size <1B (which should be prevented everywhere, IMHO), process ending before the comm is over (added sleeps on both sides) ...
