### ISSUE TITLE
Compilation issue when building in a subdirectory

### ISSUE THREAD

**Issue by mpoquet** [mquinson/simgrid#32]
I tried to compile the latest SimGrid revision this afternoon (commit 2211665cb4512) and I got several problems about missing include files. I build SimGrid in a subdirectory of the git tree (simgrid-dev/build). I'm using cmake 3.3.2 and I got the same problem with clang 3.7.0-5 and gcc 5.2.0-2. 

The following files caused problems:
* internal_config.h
* context_sysv_config.h
* portable.h

I managed to compile with some little hacks but I report the issue here since there is a problem in the building process. The compilation worked with the following hacks (executed from my git tree root):
```bash
mkdir build && cd build
cmake .. -Denable_documentation=0
make # FAIL

cd ..
ln -s ../build/src/internal_config.h src/
ln -s ../build/src/context_sysv_config.h src/
ln -s ../build/src/internal_config.h include/
ln -s ../src/portable.h include/

cd build
make # WORKS
```

**Comment by Shurakai** [comment]
I am working on this and I think I have a solution; the CMAKE_INCLUDE_CURRENT_DIR option looks promising, plus changing the INCLUDES. We shall see tomorrow.

**Comment by mquinson** [comment]
Woopsy, I broke it in https://github.com/mquinson/simgrid/commit/3203ed1f4fb6f4617e94d5351661ba07e8b8f833 I will fix it.

**Comment by mquinson** [comment]
Thanks for the report!
