### ISSUE TITLE
[MC] Catch unexpected termination of the client (with ptrace)

### ISSUE THREAD

**Issue by randomstuff** [mquinson/simgrid#33]
The current version of the model-checker is not able to detect and handle properly the unexpected termination of the model-checked process (segfault, etc.): the model-checked application dies and the model-checker continue to work without noticing it. At some point, it tries to read from the model-checked memory which fails (because the model-checked is dead).

We should probably `ptrace()` the model-checked (by default):

* ability to detect when the model-checked dies;

* ability to get the state of the model-checked when it dies (such as the recorded path in order to replay it outside of the model-checker).

## Cleaner snapshoting logic

Another benefit of using `ptrace()` is that we would implement a cleaner snapshoting/restoration logic. Currently, it relies on the fact that the (single) thread is declutching from the application contexts by switching to a specific non-snapshoted maestro stack (this maestro process not touch snapshoted data during snapshot/restores). With ptrace, we could just freeze the thread(s) and restore them as well.

## Debugging of the model-checked

However, if we `ptrace()` the model-checked we won't be able to attach it with a debugger (because a process can only be ptraced by a single tracer):

* either make the ptrace support optional (short-term solution);

* or (in the long term), let the model-checker expose a GDB-compatible socket-based debugging API (which could then be extended to add additional features -- see [rr](http://rr-project.org/) for a similar project implementing this idea).

**Comment by mquinson** [comment]
I love this ambitious idea... could you comment on how long implementing a gdb-like remote API would take?

**Comment by randomstuff** [comment]
Well the ambitious part is probably not for right now: the first thing would be to catch segfaults, SIGABRT and other crashes.

As for the GDB interface, the idea is to implement the [GDB Remote Serial Protocol](https://sourceware.org/gdb/onlinedocs/gdb/Remote-Protocol.html) which is used by GDB to connect to another "GDB server" process which exposes operations such as:

* give me the memory map of the debugged process;
* give me the list of threads in the debugged process;
* read from a file on the debugged machine;
* read/write debugged thread registers;
* read/write debugged process memory;
* insert/remote breakpoints;
* stop, continue, …

The GDB server side is implemented by different programs such as:

* [gdbserver](https://sourceware.org/gdb/current/onlinedocs/gdb/Server.html#Server);

* [rr](http://rr-project.org/) which can expose pre-recorded runs to GDB and gives GDB [reverse-debugging superpowers](http://robert.ocallahan.org/2015/10/rr-40-released-with-reverse-execution.html) in rr 4.0 (see [GdbServer](https://github.com/mozilla/rr/blob/96000078fc4068db41d5682cfddf041b2875f08c/src/GdbServer.h));

* [valgrind](http://tromey.com/blog/?p=731) in order to debugged the virtual process instead of the real process; 

* qemu (and KVM) in order to debug the emulated/guest machine (instead of the qemu process);

* the [Dolphin]() Emulator in order to debug the emulated machine and not the emulator process (see[GDBStub](https://github.com/dolphin-emu/dolphin/blob/master/Source/Core/Core/PowerPC/GDBStub.cpp)) (well in fact, this currently doesn't really work).

**Comment by randomstuff** [comment]
A first step towards debugger support would be to add support for debugging a given snapshot/checkpoint (without support for the "continue", "breakpoint" commands and so on). This way the user could look at all the checkpoints in the execution graph or when the model-checked applications crashes. I guess this should not take too long, there should not be too many GDB messages to implement. Another simple solution would be to generate core dump files.

Then we could add support for switching to the different contexts (including support for SMPI privatisation). By the way this support might be useful outside of the model-checker so we might want to avoid coupling this with the MC too much.

A next step would be to add support for actually executing code with the debugger (continue, step, breakpoint). I'm not sure how we would like to handle the interaction of the debugging and the model-checking. This might take a lot more work depending on what we want to achieve.

Then we could implement magical reverse debugging as rr does.

**Comment by randomstuff** [comment]
see #6

**Comment by randomstuff** [comment]
Switched to ptrace:

* the model-checker detects the failure of the model-checked applications;
* no support for debugging the model-checked application (GDB server) at the moment;
* but the system can still core dump the model-checked application (when the process is killed by SIGSEGV, SIGQUIT, etc.);
* we could trigger the core dumps on errors or generate them manually.
