### ISSUE TITLE
Fatal error: internal_config.h: No such file or directory (Include dirs not properly configured)

### ISSUE THREAD

**Issue by schnorr** [mquinson/simgrid#34]
I have a Debian testing. I just clone the git version from INRIA's repo, HEAD is `3bda7845c0cceaaeedd5d0371434927c8cf6231d`. Cmake runs okay, I disable the documentation option using ccmake and then hit enter after make. I end up with the following compilation error in a out-of-the-source compilation scheme (I have created a build directory in root to compile, which appears as `b` in the copy and paste below):

```
[  0%] Building CXX object CMakeFiles/simgrid.dir/src/s4u/s4u_actor.cpp.o
/usr/bin/c++   -Dsimgrid_EXPORTS -g3 -std=gnu++11 -O3 -funroll-loops -fno-strict-aliasing  
-finline-functions  -flto  -fPIC -I/home/schnorr/workspace/simgrid.git2 
-I/home/schnorr/workspace/simgrid.git2/include -I/home/schnorr/workspace/simgrid.git2/src/include  
-I/home/schnorr/workspace/simgrid.git2/b/include -I/usr/include/graphviz    -o CMakeFiles/simgrid.dir/src/s4u/s4u_actor.cpp.o -c /home/schnorr/workspace/simgrid.git2/src/s4u/s4u_actor.cpp
In file included from /home/schnorr/workspace/simgrid.git2/src/include/surf/surf.h:16:0,
                 from /home/schnorr/workspace/simgrid.git2/src/msg/msg_private.h:12,
                 from /home/schnorr/workspace/simgrid.git2/src/s4u/s4u_actor.cpp:8:
/home/schnorr/workspace/simgrid.git2/src/portable.h:13:29: fatal error: internal_config.h: No such file or directory
compilation terminated.
```

It turns out that internal_config.h is created in my build/src directory, but that dir is not include as a possible includes of the g++ and gcc commands. I have manually added the build directory in cmake but I think that is not what we want, right? I feel that a fix should pass through the edition of some cmake build configuration file, but I'm not sure exactly where.

Is this happening only with me?

**Comment by mquinson** [comment]
That's fixed in f463baf627d76634a29ab57714f4cd138f493432. Sorry, I forgot to push it to gforge git too...
