### ISSUE TITLE
java.lang.UnsatisfiedLinkError on simgrid 3.12 jar for 

### ISSUE THREAD

**Issue by orion78fr** [mquinson/simgrid#38]
`Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/simgrid-java5420305011244000193/libsimgrid.so: libboost_context.so.1.55.0: cannot open shared object file: No such file or directory`

The simgrid 3.12 jar seems to have dependancy on libboost_context.so (on Linux amd64 at least).
It may be a good idea to ship it with the jar.

**Comment by mquinson** [comment]
That's a big issue. 
Adding the library to the jar is not enough, we need the Java code to unpack it too. As
boost_context are not needed in the context of Java, I am reluctant to do so. Instead, I think that 
we need a way to generate the simgrid library with as few dependencies as possible. I will try to address this issue soon.

Thanks for reporting.

**Comment by mquinson** [comment]
That was easy to fix, actually.

**Comment by mquinson** [comment]
My previous fix was breaking when not including the lib in the jar. So I reverted the fix and reopen the bug.
