### ISSUE TITLE
Msg seems completely broken

### ISSUE THREAD

**Issue by gossa** [mquinson/simgrid#46]
With an up-to-date ubuntu:

$ make test
The following tests FAILED:
	 16 - tesh-self-bg-set-signal (Failed)
	 17 - tesh-self-catch-signal (Failed)
	 21 - graphicator (Failed)
	 43 - tesh-msg-host-on-off-thread (Failed)
	 44 - tesh-msg-host-on-off-ucontext (Failed)
	 45 - tesh-msg-host-on-off-raw (Failed)
	 46 - tesh-msg-host-on-off-wait-thread (Failed)
	 47 - tesh-msg-host-on-off-wait-ucontext (Failed)
	 48 - tesh-msg-host-on-off-wait-raw (Failed)
	 49 - tesh-msg-host-on-off-recv-thread (Failed)
	 50 - tesh-msg-host-on-off-recv-ucontext (Failed)
	 51 - tesh-msg-host-on-off-recv-raw (Failed)
	 52 - tesh-msg-host-on-off-processes-thread (Failed)
	 53 - tesh-msg-host-on-off-processes-ucontext (Failed)
	 54 - tesh-msg-host-on-off-processes-raw (Failed)
	 64 - tesh-msg-storage-basic-thread (Failed)
	 65 - tesh-msg-storage-basic-ucontext (Failed)
	 66 - tesh-msg-storage-basic-raw (Failed)
	 70 - tesh-msg-trace-thread (Failed)
	 71 - tesh-msg-trace-ucontext (Failed)
	 72 - tesh-msg-trace-raw (Failed)
	 73 - msg-file (Failed)
	 74 - msg-storage (Failed)
	 75 - msg-remote-io (Failed)
	 76 - msg-start-kill-time (Failed)
	 77 - msg-chainsend (Failed)
	 90 - msg-suspend-thread (Failed)
	 91 - msg-suspend-ucontext (Failed)
	 92 - msg-suspend-raw (Failed)
	 93 - msg-suspend-boost (Failed)
	 94 - msg-pmm (Failed)
	115 - msg-masterslave-no-crosstraffic-forwarder-thread (Failed)
	116 - msg-masterslave-no-crosstraffic-forwarder-ucontext (Failed)
	117 - msg-masterslave-no-crosstraffic-forwarder-raw (Failed)
	118 - msg-masterslave-no-crosstraffic-forwarder-boost (Failed)
	119 - msg-masterslave-no-crosstraffic-failure-thread (Failed)
	120 - msg-masterslave-no-crosstraffic-failure-ucontext (Failed)
	121 - msg-masterslave-no-crosstraffic-failure-raw (Failed)
	122 - msg-masterslave-no-crosstraffic-failure-boost (Failed)
	127 - msg-masterslave-forwarder-thread (Failed)
	128 - msg-masterslave-forwarder-ucontext (Failed)
	129 - msg-masterslave-forwarder-raw (Failed)
	130 - msg-masterslave-forwarder-boost (Failed)
	131 - msg-masterslave-failure-thread (Failed)
	132 - msg-masterslave-failure-ucontext (Failed)
	133 - msg-masterslave-failure-raw (Failed)
	134 - msg-masterslave-failure-boost (Failed)
	139 - msg-masterslave-cpu-ti-thread (Failed)
	140 - msg-masterslave-cpu-ti-ucontext (Failed)
	141 - msg-masterslave-cpu-ti-raw (Failed)
	142 - msg-masterslave-cpu-ti-boost (Failed)
	143 - msg-masterslave-vivaldi-thread (Failed)
	144 - msg-masterslave-vivaldi-ucontext (Failed)
	145 - msg-masterslave-vivaldi-raw (Failed)
	146 - msg-masterslave-vivaldi-boost (Failed)
	147 - msg-cloud-master-worker-vm-thread (Failed)
	148 - msg-cloud-master-worker-vm-ucontext (Failed)
	149 - msg-cloud-master-worker-vm-raw (Failed)
	150 - msg-cloud-master-worker-vm-boost (Failed)
	151 - msg-cloud-two-tasks-vm-thread (Failed)
	152 - msg-cloud-two-tasks-vm-ucontext (Failed)
	153 - msg-cloud-two-tasks-vm-raw (Failed)
	154 - msg-cloud-two-tasks-vm-boost (Failed)
	155 - msg-cloud-simple-vm-thread (Failed)
	156 - msg-cloud-simple-vm-ucontext (Failed)
	157 - msg-cloud-simple-vm-raw (Failed)
	158 - msg-cloud-simple-vm-boost (Failed)
	159 - msg-energy-pstates-thread (Failed)
	160 - msg-energy-pstates-boost (Failed)
	161 - msg-energy-consumption-thread (Failed)
	162 - msg-energy-consumption-ucontext (Failed)
	163 - msg-energy-consumption-raw (Failed)
	164 - msg-energy-consumption-boost (Failed)
	165 - msg-energy-onoff-thread (Failed)
	166 - msg-energy-onoff-ucontext (Failed)
	167 - msg-energy-onoff-raw (Failed)
	168 - msg-energy-onoff-boost (Failed)
	169 - msg-energy-vm-thread (Failed)
	170 - msg-energy-vm-ucontext (Failed)
	171 - msg-energy-vm-raw (Failed)
	172 - msg-energy-vm-boost (Failed)
	173 - msg-token-ring-thread (Failed)
	174 - msg-token-ring-ucontext (Failed)
	175 - msg-token-ring-raw (Failed)
	176 - msg-token-ring-boost (Failed)
	177 - msg-migration-thread (Failed)
	178 - msg-migration-ucontext (Failed)
	179 - msg-migration-raw (Failed)
	180 - msg-migration-boost (Failed)
	188 - msg-properties-thread (Failed)
	189 - msg-properties-ucontext (Failed)
	190 - msg-properties-raw (Failed)
	191 - msg-properties-boost (Failed)
	200 - msg-chord-no-crosstraffic-thread (Failed)
	201 - msg-chord-no-crosstraffic-ucontext (Failed)
	202 - msg-chord-no-crosstraffic-raw (Failed)
	203 - msg-chord-no-crosstraffic-boost (Failed)
	204 - msg-chord-no-crosstraffic-parallel-thread (Failed)
	205 - msg-chord-no-crosstraffic-parallel-ucontext (Failed)
	206 - msg-chord-no-crosstraffic-parallel-raw (Failed)
	207 - msg-chord-thread (Failed)
	208 - msg-chord-ucontext (Failed)
	209 - msg-chord-raw (Failed)
	210 - msg-chord-boost (Failed)
	211 - msg-chord-parallel-thread (Failed)
	212 - msg-chord-parallel-ucontext (Failed)
	213 - msg-chord-parallel-raw (Failed)
	214 - msg-bittorrent-thread (Failed)
	215 - msg-bittorrent-ucontext (Failed)
	216 - msg-bittorrent-raw (Failed)
	217 - msg-bittorrent-boost (Failed)
	218 - msg-bittorrent-parallel-thread (Failed)
	219 - msg-bittorrent-parallel-ucontext (Failed)
	220 - msg-bittorrent-parallel-raw (Failed)
	221 - msg-kademlia-thread (Failed)
	222 - msg-kademlia-ucontext (Failed)
	223 - msg-kademlia-raw (Failed)
	224 - msg-kademlia-boost (Failed)
	225 - msg-kademlia-parallel-thread (Failed)
	226 - msg-kademlia-parallel-ucontext (Failed)
	227 - msg-kademlia-parallel-raw (Failed)
	233 - tracing-trace-platform (Failed)
	249 - tesh-parser-bogus-missing-gw (Failed)
	251 - tesh-simdag-bypass (Failed)
	252 - tesh-simdag-flatifier (Failed)
	253 - tesh-simdag-link (Failed)
	255 - tesh-simdag-parser (Failed)
	256 - tesh-simdag-parser-sym-full (Failed)
	276 - tesh-simdag-full-links01 (SEGFAULT)
	277 - tesh-simdag-full-links02 (SEGFAULT)
	278 - tesh-simdag-one-link-g5k (SEGFAULT)
	279 - simdag-simdag (Failed)
	281 - simdag-seq-access (Failed)
	283 - simdag-fail (Failed)
	284 - simdag-avail (Failed)
	288 - simdag-prop (Failed)
	292 - java-async (Failed)
	293 - java-bittorrent (Failed)
	294 - java-bypass (Failed)
	295 - java-chord (Failed)
	296 - java-cloud (Failed)
	297 - java-cloud-migration (Failed)
	298 - java-commTime (Failed)
	299 - java-kademlia (Failed)
	300 - java-kill (Failed)
	301 - java-masterslave (Failed)
	302 - java-migration (Failed)
	303 - java-mutualExclusion (Failed)
	304 - java-pingPong (Failed)
	305 - java-priority (Failed)
	306 - java-startKillTime (Failed)
	307 - java-suspend (Failed)
	308 - java-tracing (Failed)
	309 - tesh-java-sleep-host-off (Failed)

**Comment by gossa** [comment]
The output of the simulator is:
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing' to 'no'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/categorized' to 'no'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'tracing/uncategorized' to 'no'
[0.000000] [jmsg/INFO] Using regular java threads.
[0.000000] /home/julien/repo/simgrid/src/msg/msg_host.cpp:155: [msg/WARNING] dp_objs: 1634623821 pending task?

**Comment by randomstuff** [comment]
Yes, this is known. I'm currently working on this. For reference this happens only when optimisations are enabled (and since 71c6197).

**Comment by randomstuff** [comment]
Fixed by 580571d.
