### ISSUE TITLE
smpi-energy still broken (wrong destructor call order)

### ISSUE THREAD

**Issue by mquinson** [mquinson/simgrid#47]
Hello,

The smpi-energy machines fail here, and that's because simgrid::surf::Host::onDestruction is called too late. We equiped simgrid::surf::Host with the equivalent of ObservableLifecycle, but that should be done in simgrid::Host, not sg::surf::Host.

Right now, the surf::Host is an extension and you really want it to be registered soon enough. We could hack it by finding why SMPI registers it too late, but we'd better solve the issue by moving the events and ObservableLifecylce to simgrid::Host instead.

I cannot do it right now, so feel free to proceed if you can.
Mt

**Comment by randomstuff** [comment]
Yes, I agree we should move the signals/callbacks/slots in `simgrid::host`.

**Comment by mquinson** [comment]
This is fixed in b23ab258ec14e70d63c28d53c379cd7ccc8a5809. Thus closing.
