### ISSUE TITLE
Host.all() is filled with null

### ISSUE THREAD

**Issue by gossa** [mquinson/simgrid#48]
It is impossible to get the hosts using Host.all() or Host.getByName() : both return null instead of Host.
However, Host.all() has the right size.

For instance:
Msg.info("Test : "+Host.all().length+" "+Host.all()[0]);
[controller:cloudmasterslave.Master:(1) 0.000000] [jmsg/INFO] Test : 5 null

**Comment by mquinson** [comment]
You're using the Java interface, right?
It's getting difficult to distinguish from the C++...

**Comment by randomstuff** [comment]
Does this problem happens on a specifi problem? Which version/commit of simgrid are you using?

Could you try adding this line in `pingPong/Sender.java (main)`:

      PingPongTask task;
     +Msg.info("Test : "+Host.all().length+" "+Host.all()[0]);

and see what happens wwith `ctest -R java-pingPong --verbose`?

**Comment by randomstuff** [comment]
Also you could try rebuilding SimGrid (`make clean && make`) again if you are compiling from source and see if this stil happens.

**Comment by gossa** [comment]
Its with java and since the "msg incident", I rebuild everything from scratch.
This bug appeared just after this "msg incident" was resolved.

Now I even reclone

**Comment by mquinson** [comment]
On Fri, Jan 15, 2016 at 08:43:13AM -0800, gossa wrote:
> Its with java and since the "msg incident", I rebuild everything from scratch.
> This bug appeared just after this "msg incident" was resolved.
> 
> Now I even reclone 

Reclonning should not be necessary. Could you please give us some info
about your machine? OS, version, cmake output (in particular the
bottom, where it gives the information about what it is using)?

Thanks in advance,
Mt

-- 
A wealth of information creates a poverty of attention.
          --- H.A. Simon, 1971.

**Comment by gossa** [comment]
When everything has failed (and you have messed with everything, recloning is the only hope you get.

Ubuntu 15.10 
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)


-- Cmake version 3.2.2
-- System processor: x86_64 (x86_64, 64 bits)
-- Looking for agraph.h
-- Looking for agraph.h - not found
-- Looking for cgraph.h
-- Looking for cgraph.h - not found
-- Looking for graph.h
-- Looking for graph.h - not found
-- Looking for lib agraph
-- Looking for lib agraph - not found
-- Looking for lib cgraph
-- Looking for lib cgraph - not found
-- Looking for lib graph
-- Looking for lib graph - not found
-- Looking for lib cdt
-- Looking for lib cdt - not found
-- Looking for sigc++/sigc++.h
-- Looking for sigc++/sigc++.h - not found
-- Looking for sigc++config.h
-- Looking for sigc++config.h - not found
-- Looking for libsigc++
-- Looking for libsigc++ - not found
-- Boost version: 1.58.0
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   context
Found Boost.Context API v2
-- We are using GNU dynamic linker
-- sem_open is compilable
-- sem_open is executable
-- sem_init is compilable
-- sem_init is executable
-- timedwait is compilable
-- timedlock is compilable
-- Support for ucontext factory
-- Support for thread context factory
-- Git version: 69b1e64 try again to find this lib.. and don't crash if not found
-- Git date: 2016-01-15 16:46:32 +0100
-- LTO seems usable.
-- Found Java: /usr/bin/java (found suitable version "1.7.0.91", minimum required is "1.7") 
-- Found Java: /usr/bin/java (found suitable version "1.7.0.91", minimum required is "1.7") 
-- [Java] JNI found: TRUE
-- [Java] JNI include dirs: /usr/lib/jvm/default-java/include;/usr/lib/jvm/default-java/include;/usr/lib/jvm/default-java/include
-- [Java] simgrid-java includes: /home/julien/repo/simgrid;/home/julien/repo/simgrid/include;/home/julien/repo/simgrid/src/include;/home/julien/repo/simgrid;/home/julien/repo/simgrid/include;/usr/include;/usr/include;/usr/lib/jvm/default-java/include;/usr/lib/jvm/default-java/include;/usr/lib/jvm/default-java/include
-- Doxygen version: 1.8.9.1

Configuration of package `simgrid':
        BUILDNAME ...................: UNIX
        SITE ........................: Linux_4.2.0-19-generic_x86_64
        Release .....................: simgrid-3.13-devel (release build)

        Compiler: C .................: /usr/bin/cc (GNU)
                version .............: 5.2.1
        Compiler: C++ ...............: /usr/bin/c++ (GNU)
                version .............: 5.2.1
        Compiler: Javac .............: /usr/bin/javac
                version .............: 1.7.0_91
                SWIG ................: Missing.
        Linker: .....................: /usr/bin/ld
                version .............: 2.25

        CFlags ......................:  -g3 -std=gnu11   -O3 -funroll-loops -fno-strict-aliasing  -finline-functions  -flto  
        CXXFlags ....................:  -g3 -std=gnu++11 -O3 -funroll-loops -fno-strict-aliasing  -finline-functions  -flto 
        LDFlags .....................: 
        with LTO ....................: ON

        Compile NS-3 ................: NO  (hint: )
        Compile Java ................: yes
          Native lib in jar .........: ON
        Compile Scala................: 
        Compile Lua .................: 
        Compile Smpi ................: 
        Compile MPI testsuite .......: OFF
        Compile Smpi f77 ............: 
        Compile Smpi f90 ............: 
        Compile Boost.Context support: 2

        Maintainer mode .............: OFF
        Documentation................: ON
        Model checking ..............: 0
        Tracing mode ................: ON
        Jedule  mode ................: OFF
        Latency bound ...............: OFF
        Graphviz mode ...............: 
        Sigc++ mode .................: 0
        Mallocators .................: ON

        Simgrid dependencies ........: -lm /usr/lib/x86_64-linux-gnu/libboost_context.so -pthread -lrt

        INSTALL_PREFIX ..............: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/julien/repo/simgrid

**Comment by randomstuff** [comment]
Fixed by f2e9bf81aebf9a0d39563c3f955fc24e9270d74f.

**Comment by mquinson** [comment]
It's fixed, thus closing. Thanks to all for reporting and the help to fix it.
