### ISSUE TITLE
CMake doesn't correctly check for valgrind and graphviz

### ISSUE THREAD

**Issue by Shurakai** [mquinson/simgrid#49]
I installed Debian Testing on my new system and ran cmake, which returned without problems. I then ran make and after 3%, I get these errors:

src/simdag/sd_dotloader.c:20:29: fatal error: graphviz/cgraph.h: No such file or directory

src/simix/smx_context.c:32:32: fatal error: valgrind/valgrind.h: No such file or directory

Shouldn't cmake already tell me that I am missing these libraries?

**Comment by mquinson** [comment]
Is it possible that you copied your SimGrid checkout tree over to your new machine?

If I uninstall valgrind and rebuild, I get the same error, even if I force CMake to rerun.
But if I remove CMakeCache, it then works like a charm. Did you retain your CMakeCache also?

Note that I only investigated valgrind so far. I didn't checked for graphviz

**Comment by Shurakai** [comment]
Of course, you're right. Absolutely my fault :( Closing...

**Comment by mquinson** [comment]
no problem ;)
