### ISSUE TITLE
Change the smpirun script to make the -wrapper option more intuitive

### ISSUE THREAD

**Issue by Shurakai** [mquinson/simgrid#58]
If a developer wants to use gdb interactively with smpirun, he has to add 

   -wrapper "gdb --args" -foreground

It is quite unintuitive that the -foreground option is necessary and I believe we should fix that. Unfortunately, @randomstuff argues that there are use cases where "-foreground" is not wanted with -wrapper; a -gdb option is also not a solution since -wrapper is useful with many tools.

Background: The -foreground option was introduced by @randomstuff in fefd7e29e7bf5ae19e8421232861fe17c6115c9f to make sure that sub-processes terminate before the script terminates (if it receives a signal); otherwise, they would become zombies after they terminated. We did have many zombies on the CI servers, so this change was introduced.

Thanks @stanisic for reporting this issue.

**Comment by randomstuff** [comment]
Summary (as far as I remember): In order to kill the child process from the sh script, we have to run it in the background. By running it in the background the shell, connects the child process stdin to `/dev/null` and programs such as GDB are not happy anymore.

With `bash` we can avoid this with `$my_program $my_args <&0 &` but it does not work with `dash` (and probably other shells).

One solution would be to use another language for `smpirun` instead of `sh`.

**Comment by mquinson** [comment]
What about introducing a --with-gdb option that would be a shortcut for all the necessary mess under the hood?

**Comment by randomstuff** [comment]
@mquinson, Yes it might be an idea. However, someong might want to use another debugger (lldb?) or might need foreground for another reason.

**Comment by mquinson** [comment]
I was not speaking of removing the -foreground option but to offer an easy to go option for the most common use case. In my mind, ```--with-gdb``` would do exactly as if ```-wrapper "gdb --args" -foreground``` would be provided. It should be an error to combine ```--with-gdb``` with the options of the other set.

**Comment by randomstuff** [comment]
> It should be an error to combine --with-gdb with the options of the other set.

Or `--with-gdb` could preprend `gdb --args` to the arguments (`${DEBUGGER} ${WRAPPER} ${EXEC} ${TRACEOPTIONS} ${SIMOPTS} ${PLATFORMTMP} ${APPLICATIONTMP}`).

**Comment by randomstuff** [comment]
I think we should be able to get rid of this `-foreground` option with a construct like this:

    # Keep a copy of stdin in order to give it back to the background job:
    exec 3<&0
    ${EXEC} ${TRACEOPTIONS} ${SIMOPTS} ${PLATFORMTMP} ${APPLICATIONTMP} <&3 &
    pid="$!"
    exec 3>&-
    wait "$pid"

**Comment by randomstuff** [comment]
I removed the need for `-foreground` :relieved: with the horrible hack I mentioned.

The argument is still accepted (but ignored) for compatibility.
