### ISSUE TITLE
Cannot build SimGrid 3.12 on mac 

### ISSUE THREAD

**Issue by aliomarabdelazim** [mquinson/simgrid#63]
Hi, 
 I’m trying to install SimGrid 3.12 on mac book pro, I have downloaded the source and when I used clang compiler to compile it, i got a lot of file not found errors, so I used GNU C compiler, in the terminal I wrote , 
“cmake -DCMAKE_C_COMPILER=gcc-5  -DCMAKE_CXX_COMPILER=G++-5 -DCC=gcc-5 -DCXX=g++-5 -DCMAKE_INSTALL_PREFIX=/opt/simgrid .”  

and the output is 
“ Cmake version 3.4.3
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-5
-- Check for working C compiler: /usr/local/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/G++-5
-- Check for working CXX compiler: /usr/local/bin/G++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Warning (dev) at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:88 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "CXX" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/CMakeTestCXXCompiler.cmake:68 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:5 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAVE_C_STACK_CLEANER
-- Performing Test HAVE_C_STACK_CLEANER - Failed
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_C11
-- Performing Test COMPILER_SUPPORTS_C11 - Success
-- Found Perl: /usr/bin/perl (found version "5.18.2") 
-- System processor: x86_64 (x86_64, 64 bits)
-- Looking for agraph.h
-- Looking for agraph.h - not found
-- Looking for cgraph.h
-- Looking for cgraph.h - found
-- Looking for graph.h
-- Looking for graph.h - not found
-- Looking for lib agraph
-- Looking for lib agraph - not found
-- Looking for lib cgraph
-- Looking for lib cgraph - found
-- Looking for lib graph
-- Looking for lib graph - not found
-- Looking for lib cdt
-- Looking for lib cdt - found
-- Looking for sigc++/sigc++.h
-- Looking for sigc++/sigc++.h - not found
-- Looking for sigc++config.h
-- Looking for sigc++config.h - not found
-- Looking for libsigc++
-- Looking for libsigc++ - not found
-- Boost version: 1.60.0
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   context
Found Boost.Context API v2
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for backtrace in execinfo
-- Looking for backtrace in execinfo - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for sem_init in pthread
-- Looking for sem_init in pthread - found
-- Looking for sem_open in pthread
-- Looking for sem_open in pthread - found
-- Looking for sem_timedwait in pthread
-- Looking for sem_timedwait in pthread - not found
-- Looking for pthread_mutex_timedlock in pthread
-- Looking for pthread_mutex_timedlock in pthread - not found
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Looking for valgrind/valgrind.h
-- Looking for valgrind/valgrind.h - not found
-- Looking for socket.h
-- Looking for socket.h - not found
-- Looking for stat.h
-- Looking for stat.h - not found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/ptrace.h
-- Looking for sys/ptrace.h - not found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for errno.h
-- Looking for errno.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/param.h
-- Looking for sys/param.h - found
-- Looking for sys/sysctl.h
-- Looking for sys/sysctl.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for ucontext.h
-- Looking for ucontext.h - found
-- Looking for stdio.h
-- Looking for stdio.h - found
-- Looking for linux/futex.h
-- Looking for linux/futex.h - not found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for getdtablesize
-- Looking for getdtablesize - found
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for readv
-- Looking for readv - found
-- Looking for popen
-- Looking for popen - found
-- Looking for signal
-- Looking for signal - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for vsnprintf
-- Looking for vsnprintf - found
-- Looking for asprintf
-- Looking for asprintf - found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for makecontext
-- Looking for makecontext - found
-- Looking for process_vm_readv
-- Looking for process_vm_readv - not found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for bin gfortran
-- SMPI Fortran is disabled on Windows and MacOS platforms. Please contact the SimGrid team if you need it.
-- Fortran support for smpi is disabled.
-- Warning:  no support for SMPI automatic privatization on this platform
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- We are using GNU dynamic linker
-- sem_open is compilable
-- sem_open is executable
/Users/abdelazi/simgrid/tools/cmake/test_prog/prog_sem_init.c: In function 'main':
/Users/abdelazi/simgrid/tools/cmake/test_prog/prog_sem_init.c:15:3: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
   if (sem_init(&s, 0, 0) != 0) 
   ^
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/semaphore.h:29:0,
                 from /Users/abdelazi/simgrid/tools/cmake/test_prog/prog_sem_init.c:10:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sys/semaphore.h:55:5: note: declared here
 int sem_init(sem_t *, int, unsigned int) __deprecated;
     ^
-- sem_init is compilable
-- Bin /Users/abdelazi/simgrid/sem_init exists!
-- Warning: sem_init not executable
-- Compilation output: ''
-- Exit result of sem_init: 1
-- Support for thread context factory
-- Git version: 7f819b2 more cleanups in XML files
-- Git date: 2016-02-18 14:14:03 +0100
-- LTO does not seem usable -- try updating your build chain.
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.11") 
-- Doxygen version: 1.8.11

Configuration of package `simgrid':
        BUILDNAME ...................: APPLE
        SITE ........................: Darwin_15.3.0_x86_64
        Release .....................: simgrid-3.13-devel (release build)

        Compiler: C .................: /usr/local/bin/gcc-5 (GNU)
                version .............: 5.2.0
        Compiler: C++ ...............: /usr/local/bin/G++-5 (GNU)
                version .............: 5.2.0
        Linker: .....................: /usr/bin/ld
                version .............: 

        CFlags ......................:  -g3 -std=gnu11   -O3 -funroll-loops -fno-strict-aliasing  -finline-functions   -D_XOPEN_SOURCE=700 -D_DARWIN_C_SOURCE
        CXXFlags ....................:  -g3 -std=gnu++11 -O3 -funroll-loops -fno-strict-aliasing  -finline-functions 
        LDFlags .....................: -Wl,-search_paths_first -Wl,-headerpad_max_install_names
        with LTO ....................: OFF

        Compile NS-3 ................: NO  (hint: )
        Compile Java ................: NO
        Compile Scala................: 
        Compile Lua .................: 
        Compile Smpi ................: 1
        Compile MPI testsuite .......: OFF
        Compile Smpi f77 ............: 0
        Compile Smpi f90 ............: 0
        Compile Boost.Context support: 2

        Maintainer mode .............: OFF
        Documentation................: ON
        Model checking ..............: 0
        Tracing mode ................: ON
        Jedule  mode ................: OFF
        Latency bound ...............: OFF
        Graphviz mode ...............: 1
        Sigc++ mode .................: 0
        Mallocators .................: ON

        Simgrid dependencies ........: -lm /usr/local/lib/libboost_context-mt.dylib -lcgraph -Wl,-U -Wl,_smpi_simulated_main

        INSTALL_PREFIX ..............: /opt/simgrid
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   simgrid

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CC
“ 

After that I typed make and it stopped at 5% 
“[ %5 ] Building CXX object CMakeFiles/simgrid.dir/src/simdag/sd_dotloader.cpp.o
In file included from /Users/abdelazi/simgrid/include/xbt/sysdep.h:14:0,
                 from /Users/abdelazi/simgrid/include/xbt.h:13,
                 from /Users/abdelazi/simgrid/include/simgrid/forward.h:10,
                 from /Users/abdelazi/simgrid/include/simgrid/link.h:12,
                 from /Users/abdelazi/simgrid/include/simgrid/simdag.h:14,
                 from /Users/abdelazi/simgrid/src/simdag/simdag_private.h:11,
                 from /Users/abdelazi/simgrid/src/simdag/sd_dotloader.cpp:7:
/Users/abdelazi/simgrid/src/simdag/sd_dotloader.cpp: In function 'xbt_dynar_s* SD_dotload_generic(const char*, seq_par_t, bool)':
/Users/abdelazi/simgrid/src/simdag/sd_dotloader.cpp:251:101: error: 'basename' was not declared in this scope
     XBT_ERROR("The DOT described in %s is not a DAG. It contains a cycle.", basename((char*)filename));
                                                                                                     ^
/Users/abdelazi/simgrid/include/xbt/log.h:649:40: note: in definition of macro XBT_ERROR'
           _xbt_log_event_log(&_log_ev, __VA_ARGS__);                        \
                                        ^
make[2]: *** [CMakeFiles/simgrid.dir/src/simdag/sd_dotloader.cpp.o] Error 1
make[1]: *** [CMakeFiles/simgrid.dir/all] Error 2
make: *** [all] Error 2”

anyone can help ?

**Comment by mquinson** [comment]
Could you give a try to the current development version, please? The one from the git.

**Comment by frs69wq** [comment]
I don't think the git version will change anything. The issue seems to be related to the basename function used by the dot loader. It requires libgen.h that might not be installed on your machine.

**Comment by aliomarabdelazim** [comment]
I tried to install simGrid 3.11 and the installation completed without any errors, but i still couldn’t install simGrid 3.12


Ali Omar Abdelazim Mohammed

Departement Mathematik & Informatik
High Performance Computing Group
Universität Basel
Spiegelgasse 1
CH-4051 Basel Switzerland
email: ali.omarabdelazimmohammed@unibas.ch<mailto:ali.omarabdelazimmohammed@unibas.ch>
Phone: +41 (0)61 267 05 41

On 23 Feb 2016, at 09:20, Frederic Suter <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think the git version will change anything. The issue seems to be related to the basename function used by the dot loader. It requires libgen.h that might not be installed on your machine.

**Comment by aliomarabdelazim** [comment]
I installed the version from git (SimGrid 3.13) without any problems, 
thanks

**Comment by mquinson** [comment]
I'm closing this issue since it works in the git.

Thanks for reporting,
Mt

**Comment by aliomarabdelazim** [comment]
Hello,

I have a question about SIMGrid and I could not find the answer online, What is the time resolution of sigrid, meaning what is the smallest time unit that simgrid simulator can simulate in case of task execution or communication ?
Best regards,
Ali

Ali Omar Abdelazim Mohammed
Departement Mathematik & Informatik
High Performance Computing Group
Universität Basel
Spiegelgasse 1
CH-4051 Basel Switzerland
email: ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch>
Phone: +41 (0)61 267 05 41

On 23 Feb 2016, at 09:32, Ali Omar Abdelazim Mohammed <ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch>> wrote:

I tried to install simGrid 3.11 and the installation completed without any errors, but i still couldn’t install simGrid 3.12


Ali Omar Abdelazim Mohammed

Departement Mathematik & Informatik
High Performance Computing Group
Universität Basel
Spiegelgasse 1
CH-4051 Basel Switzerland
email: ali.omarabdelazimmohammed@unibas.ch<mailto:ali.omarabdelazimmohammed@unibas.ch>
Phone: +41 (0)61 267 05 41

On 23 Feb 2016, at 09:20, Frederic Suter <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think the git version will change anything. The issue seems to be related to the basename function used by the dot loader. It requires libgen.h that might not be installed on your machine.

**Comment by frs69wq** [comment]
Hi

By default the precision of the simulation kernel is set to th 
microsecond, but you can increase it by adding --cfg=surf/precision:1-e9 
'for nanosecond precision) to your command line.

Best

Le 31/03/2016 12:15, aliomarabdelazim a écrit :
> Hello,
>
> I have a question about SIMGrid and I could not find the answer 
> online, What is the time resolution of sigrid, meaning what is the 
> smallest time unit that simgrid simulator can simulate in case of task 
> execution or communication ?
> Best regards,
> Ali
>
> Ali Omar Abdelazim Mohammed
> Departement Mathematik & Informatik
> High Performance Computing Group
> Universität Basel
> Spiegelgasse 1
> CH-4051 Basel Switzerland
> email: ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch>
> Phone: +41 (0)61 267 05 41
>
> On 23 Feb 2016, at 09:32, Ali Omar Abdelazim Mohammed 
> <ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch>> wrote:
>
> I tried to install simGrid 3.11 and the installation completed without 
> any errors, but i still couldn’t install simGrid 3.12
>
>
> Ali Omar Abdelazim Mohammed
>
> Departement Mathematik & Informatik
> High Performance Computing Group
> Universität Basel
> Spiegelgasse 1
> CH-4051 Basel Switzerland
> email: 
> ali.omarabdelazimmohammed@unibas.ch<mailto:ali.omarabdelazimmohammed@unibas.ch>
> Phone: +41 (0)61 267 05 41
>
> On 23 Feb 2016, at 09:20, Frederic Suter 
> <notifications@github.com<mailto:notifications@github.com>> wrote:
>
>
> I don't think the git version will change anything. The issue seems to 
> be related to the basename function used by the dot loader. It 
> requires libgen.h that might not be installed on your machine.
>
> —
> Reply to this email directly or view it on 
> GitHub<https://github.com/mquinson/simgrid/issues/63#issuecomment-187598417>.
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/mquinson/simgrid/issues/63#issuecomment-203865969>
>

-- 
One should, for example, be able to see that things are hopeless
and yet be determined to make them otherwise.
                                           -- F. Scott Fitzgerald

**Comment by aliomarabdelazim** [comment]
Thanks for your quick reply,
I have tried --cfg=surf/precision:1-e9  and with tasks of 10 flops on 1Gf hosts and still I get the execution time is zero, is this means that is calculated but not printed on the screen because of XBT_INFO ? or that means that the simulated execution time is zero ?
Best regards,
Ali



On 31 Mar 2016, at 12:25, Frederic Suter <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi

By default the precision of the simulation kernel is set to th
microsecond, but you can increase it by adding --cfg=surf/precision:1-e9
'for nanosecond precision) to your command line.

Best

Le 31/03/2016 12:15, aliomarabdelazim a écrit :
> Hello,
>
> I have a question about SIMGrid and I could not find the answer
> online, What is the time resolution of sigrid, meaning what is the
> smallest time unit that simgrid simulator can simulate in case of task
> execution or communication ?
> Best regards,
> Ali
>
> Ali Omar Abdelazim Mohammed
> Departement Mathematik & Informatik
> High Performance Computing Group
> Universität Basel
> Spiegelgasse 1
> CH-4051 Basel Switzerland
> email: ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch><mailto:ali.mohammed@unibas.ch>
> Phone: +41 (0)61 267 05 41
>
> On 23 Feb 2016, at 09:32, Ali Omar Abdelazim Mohammed
> <ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch><mailto:ali.mohammed@unibas.ch>> wrote:
>
> I tried to install simGrid 3.11 and the installation completed without
> any errors, but i still couldn’t install simGrid 3.12
>
>
> Ali Omar Abdelazim Mohammed
>
> Departement Mathematik & Informatik
> High Performance Computing Group
> Universität Basel
> Spiegelgasse 1
> CH-4051 Basel Switzerland
> email:
> ali.omarabdelazimmohammed@unibas.ch<mailto:ali.omarabdelazimmohammed@unibas.ch><mailto:ali.omarabdelazimmohammed@unibas.ch>
> Phone: +41 (0)61 267 05 41
>
> On 23 Feb 2016, at 09:20, Frederic Suter
> <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:
>
>
> I don't think the git version will change anything. The issue seems to
> be related to the basename function used by the dot loader. It
> requires libgen.h that might not be installed on your machine.
>
> —
> Reply to this email directly or view it on
> GitHub<https://github.com/mquinson/simgrid/issues/63#issuecomment-187598417>.
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mquinson/simgrid/issues/63#issuecomment-203865969>
>

--
One should, for example, be able to see that things are hopeless
and yet be determined to make them otherwise.
-- F. Scott Fitzgerald

**Comment by mquinson** [comment]
Please don't reuse the same github entry for an unrelated problem.
Please either open a new issue, or send us an email to
simgrid-user@lists.gforge.inria.fr

That being said, I don't have a perfect answer about the surf
precision. Does it work for 100kf hosts? For 10kf hosts? You can also
try to experiment with the other precision parameter, ie
maxmin/precision that is documented as follows:

  The analytical models handle a lot of floating point values. It is
  possible to change the epsilon used to update and compare them
  through the maxmin/precision item (default value: 0.00001). Changing
  it may speedup the simulation by discarding very small actions, at
  the price of a reduced numerical precision.

Bye, Mt.

On Thu, Mar 31, 2016 at 03:41:30AM -0700, aliomarabdelazim wrote:
> Thanks for your quick reply,
> I have tried --cfg=surf/precision:1-e9  and with tasks of 10 flops on 1Gf hosts and still I get the execution time is zero, is this means that is calculated but not printed on the screen because of XBT_INFO ? or that means that the simulated execution time is zero ?
> Best regards,
> Ali
> 
> 
> 
> On 31 Mar 2016, at 12:25, Frederic Suter <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> Hi
> 
> By default the precision of the simulation kernel is set to th
> microsecond, but you can increase it by adding --cfg=surf/precision:1-e9
> 'for nanosecond precision) to your command line.
> 
> Best
> 
> Le 31/03/2016 12:15, aliomarabdelazim a écrit :
> > Hello,
> >
> > I have a question about SIMGrid and I could not find the answer
> > online, What is the time resolution of sigrid, meaning what is the
> > smallest time unit that simgrid simulator can simulate in case of task
> > execution or communication ?
> > Best regards,
> > Ali
> >
> > Ali Omar Abdelazim Mohammed
> > Departement Mathematik & Informatik
> > High Performance Computing Group
> > Universität Basel
> > Spiegelgasse 1
> > CH-4051 Basel Switzerland
> > email: ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch><mailto:ali.mohammed@unibas.ch>
> > Phone: +41 (0)61 267 05 41
> >
> > On 23 Feb 2016, at 09:32, Ali Omar Abdelazim Mohammed
> > <ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch><mailto:ali.mohammed@unibas.ch>> wrote:
> >
> > I tried to install simGrid 3.11 and the installation completed without
> > any errors, but i still couldn’t install simGrid 3.12
> >
> >
> > Ali Omar Abdelazim Mohammed
> >
> > Departement Mathematik & Informatik
> > High Performance Computing Group
> > Universität Basel
> > Spiegelgasse 1
> > CH-4051 Basel Switzerland
> > email:
> > ali.omarabdelazimmohammed@unibas.ch<mailto:ali.omarabdelazimmohammed@unibas.ch><mailto:ali.omarabdelazimmohammed@unibas.ch>
> > Phone: +41 (0)61 267 05 41
> >
> > On 23 Feb 2016, at 09:20, Frederic Suter
> > <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:
> >
> >
> > I don't think the git version will change anything. The issue seems to
> > be related to the basename function used by the dot loader. It
> > requires libgen.h that might not be installed on your machine.
> >
> > —
> > Reply to this email directly or view it on
> > GitHub<https://github.com/mquinson/simgrid/issues/63#issuecomment-187598417>.
> >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mquinson/simgrid/issues/63#issuecomment-203865969>
> >
> 
> --
> One should, for example, be able to see that things are hopeless
> and yet be determined to make them otherwise.
> -- F. Scott Fitzgerald
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<https://github.com/mquinson/simgrid/issues/63#issuecomment-203869643>
> 
> 
> 
> ---
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/mquinson/simgrid/issues/63#issuecomment-203874391

-- 
Nos péchés sont têtus, nos repentirs sont lâches
          --- Ch.Baudelaire, Les fleurs du mal

**Comment by aliomarabdelazim** [comment]
Thank you for the reply, and sorry for using the same topic again.
Best regards,
Ali



On 01 Apr 2016, at 10:10, Martin Quinson <notifications@github.com<mailto:notifications@github.com>> wrote:

Please don't reuse the same github entry for an unrelated problem.
Please either open a new issue, or send us an email to
simgrid-user@lists.gforge.inria.fr<mailto:simgrid-user@lists.gforge.inria.fr>

That being said, I don't have a perfect answer about the surf
precision. Does it work for 100kf hosts? For 10kf hosts? You can also
try to experiment with the other precision parameter, ie
maxmin/precision that is documented as follows:

The analytical models handle a lot of floating point values. It is
possible to change the epsilon used to update and compare them
through the maxmin/precision item (default value: 0.00001). Changing
it may speedup the simulation by discarding very small actions, at
the price of a reduced numerical precision.

Bye, Mt.

On Thu, Mar 31, 2016 at 03:41:30AM -0700, aliomarabdelazim wrote:
> Thanks for your quick reply,
> I have tried --cfg=surf/precision:1-e9 and with tasks of 10 flops on 1Gf hosts and still I get the execution time is zero, is this means that is calculated but not printed on the screen because of XBT_INFO ? or that means that the simulated execution time is zero ?
> Best regards,
> Ali
>
>
>
> On 31 Mar 2016, at 12:25, Frederic Suter <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:
>
> Hi
>
> By default the precision of the simulation kernel is set to th
> microsecond, but you can increase it by adding --cfg=surf/precision:1-e9
> 'for nanosecond precision) to your command line.
>
> Best
>
> Le 31/03/2016 12:15, aliomarabdelazim a écrit :
> > Hello,
> >
> > I have a question about SIMGrid and I could not find the answer
> > online, What is the time resolution of sigrid, meaning what is the
> > smallest time unit that simgrid simulator can simulate in case of task
> > execution or communication ?
> > Best regards,
> > Ali
> >
> > Ali Omar Abdelazim Mohammed
> > Departement Mathematik & Informatik
> > High Performance Computing Group
> > Universität Basel
> > Spiegelgasse 1
> > CH-4051 Basel Switzerland
> > email: ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch><mailto:ali.mohammed@unibas.ch><mailto:ali.mohammed@unibas.ch>
> > Phone: +41 (0)61 267 05 41
> >
> > On 23 Feb 2016, at 09:32, Ali Omar Abdelazim Mohammed
> > <ali.mohammed@unibas.ch<mailto:ali.mohammed@unibas.ch><mailto:ali.mohammed@unibas.ch><mailto:ali.mohammed@unibas.ch>> wrote:
> >
> > I tried to install simGrid 3.11 and the installation completed without
> > any errors, but i still couldn’t install simGrid 3.12
> >
> >
> > Ali Omar Abdelazim Mohammed
> >
> > Departement Mathematik & Informatik
> > High Performance Computing Group
> > Universität Basel
> > Spiegelgasse 1
> > CH-4051 Basel Switzerland
> > email:
> > ali.omarabdelazimmohammed@unibas.ch<mailto:ali.omarabdelazimmohammed@unibas.ch><mailto:ali.omarabdelazimmohammed@unibas.ch><mailto:ali.omarabdelazimmohammed@unibas.ch>
> > Phone: +41 (0)61 267 05 41
> >
> > On 23 Feb 2016, at 09:20, Frederic Suter
> > <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:
> >
> >
> > I don't think the git version will change anything. The issue seems to
> > be related to the basename function used by the dot loader. It
> > requires libgen.h that might not be installed on your machine.
> >
> > —
> > Reply to this email directly or view it on
> > GitHub<https://github.com/mquinson/simgrid/issues/63#issuecomment-187598417>.
> >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mquinson/simgrid/issues/63#issuecomment-203865969>
> >
>
> --
> One should, for example, be able to see that things are hopeless
> and yet be determined to make them otherwise.
> -- F. Scott Fitzgerald
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<https://github.com/mquinson/simgrid/issues/63#issuecomment-203869643>
>
>
>
> ---
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/mquinson/simgrid/issues/63#issuecomment-203874391

--
Nos péchés sont têtus, nos repentirs sont lâches
--- Ch.Baudelaire, Les fleurs du mal
