### ISSUE TITLE
 Problematic frame: # C  [libsimgrid.so+0xb2366]

### ISSUE THREAD

**Issue by kenenbek** [mquinson/simgrid#70]
I tried to run TracingTest.java of example/java/tracing folder.
But java says:
Could you have any advises to fix it? I run "ulimit -c unlimited" but I didn't help.
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f691200f366, pid=6861, tid=140090217649920
#
# JRE version: OpenJDK Runtime Environment (8.0_72-b15) (build 1.8.0_72-internal-b15)
# Java VM: OpenJDK 64-Bit Server VM (25.72-b15 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libsimgrid.so+0xb2366]
#
# Core dump written. Default location: /home/ken/Downloads/SimGrid-3.12/examples/java/core or core.6861
#
# An error report file with more information is saved as:
# /home/ken/Downloads/SimGrid-3.12/examples/java/hs_err_pid6861.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by mquinson** [comment]
What was the exact command line that you used?

**Comment by kenenbek** [comment]
1)I opened **tracing** project in Intellij Idea.
2) Added **simgrid.jar** as library. 
3) In **edit configurations** I set up ways to platform.xml and Deployment.xml
4) I run TracingTest.class and have this error notofication.

**Comment by kenenbek** [comment]
@mquinson Sorry, I did a mistake. 
I have another question simgrid-java is only for MSG simulations? Can I use java for SMPI and SimDag?

**Comment by mquinson** [comment]
You mean that this issue is solved? Could you tell us how you did that (for the next guy experiencing the same issue)?

About your new question, yes. Only MSG is ported to Java so far. SimDag would not be very difficult if you want to do it, but I don't see how you could do that for MPI. I don't know any java implementation of MPI, do you?

**Comment by mquinson** [comment]
The best thing would be to discuss live on IRC. Please click on that link: webchat.oftc.net/?nick=kenenbek&channels=%23simgrid&uio=d4 and then on the connect button.

**Comment by kenenbek** [comment]
I had to add **--cfg=tracing:yes  --cfg=tracing/filename:simulation.trace --cfg=tracing/platform:yes **for program variables.

**Comment by kenenbek** [comment]
fgdf

**Comment by kenenbek** [comment]
Hello, Monsieur Martin. Could you help? In the master-slave type of simulation, how can I retrieve what task(name and size) currently Slave performs.

**Comment by mquinson** [comment]
You have to save it yourself when you start the task.  There is no way to retrieve from simgrid afterward. 


Rédigé sur appareil mobile,  dsl des typos et de la brièveté. 

-------- Message d'origine --------
De : kenenbek <notifications@github.com> 
Date : 31/03/2016  16:10  (GMT+01:00) 
À : mquinson/simgrid <simgrid@noreply.github.com> 
Cc : Martin Quinson <martin.quinson@irisa.fr> 
Objet : Re: [mquinson/simgrid]  Problematic frame: # C 
  [libsimgrid.so+0xb2366] (#70) 

Hello, Monsieur Martin. Could you help? In the master-slave type of simulation, how can I retrieve what task(name and size) currently Slave performs.

**Comment by kenenbek** [comment]
You offer to create array where I will store all Tasks and Hosts associated with this task? Maybe there is more simgrid-native way to retrieve Task performing on the given host?

**Comment by kenenbek** [comment]
https://github.com/mquinson/simgrid/blob/master/examples/java/tracing/Sender.java

Could you explain, s'il vous plaît, how SimGrid knows to which colors processes will be assigned? (or it is random)
What does Trace.hostPopState() do? _Pop the last value of a state of a given host_. But what "pop" means?

**Comment by mquinson** [comment]
None that I am aware of,  unfortunately. 


Rédigé sur appareil mobile,  dsl des typos et de la brièveté. 

-------- Message d'origine --------
De : kenenbek <notifications@github.com> 
Date : 31/03/2016  17:36  (GMT+01:00) 
À : mquinson/simgrid <simgrid@noreply.github.com> 
Cc : Martin Quinson <martin.quinson@irisa.fr> 
Objet : Re: [mquinson/simgrid]  Problematic frame: # C 
  [libsimgrid.so+0xb2366] (#70) 

You offer to create array where I will store all Tasks and Hosts associated with this task? Maybe there is more simgrid-native way to retrieve Task performing on the given host?

**Comment by mquinson** [comment]
Nope.  I will  not answer any unrelated unconstructed requests on the github bug tracker. Please (properly) use the relevant mailing list. 




Rédigé sur appareil mobile,  dsl des typos et de la brièveté. 

-------- Message d'origine --------
De : kenenbek <notifications@github.com> 
Date : 31/03/2016  21:44  (GMT+01:00) 
À : mquinson/simgrid <simgrid@noreply.github.com> 
Cc : Martin Quinson <martin.quinson@irisa.fr> 
Objet : Re: [mquinson/simgrid]  Problematic frame: # C 
  [libsimgrid.so+0xb2366] (#70) 

https://github.com/mquinson/simgrid/blob/master/examples/java/tracing/Sender.java

Could you explain, s'il vous plaît, how SimGrid knows to which colors processes will be assigned? (or it is random)

What does Trace.hostPopState() do? Pop the last value of a state of a given host. But what "pop" means?

**Comment by kenenbek** [comment]
Sorry, I have spent today 7 hours to find answer and looking into code.
After I had failed and wrote here. Sorry, sorry, sorry.

**Comment by mquinson** [comment]
No problem. Just start using the mailing list properly and everything is fine. 


Rédigé sur appareil mobile,  dsl des typos et de la brièveté. 

-------- Message d'origine --------
De : kenenbek <notifications@github.com> 
Date : 31/03/2016  23:56  (GMT+01:00) 
À : mquinson/simgrid <simgrid@noreply.github.com> 
Cc : Martin Quinson <martin.quinson@irisa.fr> 
Objet : Re: [mquinson/simgrid]  Problematic frame: # C 
  [libsimgrid.so+0xb2366] (#70) 

Sorry, I have spent today 7 hours to find answer and looking into code.

After I had failed and wrote here. Sorry, sorry, sorry.
