### ISSUE TITLE
Host().getLoad isn't implemented? 

### ISSUE THREAD

**Issue by kenenbek** [mquinson/simgrid#73]
I'm trying to use this method, but error pops.
`/builds/workspace/SimGrid-Multi/build_mode/Debug/node/simgrid-debian-wheezy-64/build/SimGrid-3.12/src/msg/msg_host.c:226: [xbt/CRITICAL] Not implemented yet`

**Comment by frs69wq** [comment]
This is not an error, but a comprehensive message saying that the function is not implemented yet. I suppose this answer your question by itself. 

Moreover, if you look for this function in this github repository, you'll find that this unimplemented function has been removed by commits de3208adefb5c1fc6ceccde40f01486db3d89d2f (in C) c9e7a3171bb86b00cb3ed20e492750d25bfa89e3 (in the Java bindings). There was even a previous (closed) issue on that function https://github.com/mquinson/simgrid/issues/14

**Comment by kenenbek** [comment]
Is there any hope that this method will be implemented soon?

**Comment by mquinson** [comment]
Unfortunately, not. we do not have the necessary manpower. I'm really sorry.
