### ISSUE TITLE
Test msg-exception is disabled 

### ISSUE THREAD

**Issue by mquinson** [mquinson/simgrid#8]
This test is expected to display a backtrace, which is not portable across computers (full path to source files is displayed). I seem to remember that there is a way to get "short" backtraces, but I am not sure and I've no idea of how.

The easier could be to change the test to avoid the backtrace (catch it and test programatically that it has the right form, whatever it may be).

**Comment by alegrand** [comment]
Hi,

Le 28/04/2015 18:22, Martin Quinson a écrit :
> This test is expected to display a backtrace, which is not portable
> across computers (full path to source files is displayed). I seem to
> remember that there is a way to get "short" backtraces, but I am not
> sure and I've no idea of how.
> 
> The easier could be to change the test to avoid the backtrace (catch it
> and test programatically that it has the right form, whatever it may be).

Christian actually came to me this morning to ask me about it and he's
on it, setting up a workaround. It will be fixed very soon.

    Arnaud

**Comment by mquinson** [comment]
No problem of course. I just opened the bug report so that we don't loose track of that issue.

Thanks,

**Comment by Shurakai** [comment]
This was fixed; we use --cfg=exception/cutpath to do this.
