### ISSUE TITLE
Cannot use simgrid_full.jar on Linux

### ISSUE THREAD

**Issue by randomstuff** [mquinson/simgrid#9]
It seems I'm having a similar issue to #5 on my Debian box if I'm trying to use the `simgrid_full.jar` (instead of relying of systemwide simgrid `.so`) files:

<pre>$ java -cp .:simgrid_full.jar kademlia.Kademlia ../platforms/platform.xml kademlia/kademlia.xml
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/simgrid-java-8378003860515004911.tmp: libsimgrid.so.3.12: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at org.simgrid.NativeLib.loadLib(NativeLib.java:89)
	at org.simgrid.NativeLib.nativeInit(NativeLib.java:43)
	at org.simgrid.msg.Msg.nativeInit(Msg.java:20)
	at org.simgrid.msg.Msg.<clinit>(Msg.java:25)
	at kademlia.Kademlia.main(Kademlia.java:16)
</pre>

This happen when trying to load `libsimgrid-java`:

<pre>
NativeLib.nativeInit("simgrid");
NativeLib.nativeInit("simgrid-java");
</pre>

There is no `libsimgrid.so.3.12` in the JAR anyway, only `libsimgrid.so`.

**Comment by randomstuff** [comment]
Maybe we should we change the SONAME and NEEDED fields in the full JAR?

**Comment by randomstuff** [comment]
Maybe we should we change the `DT_SONAME` and `DT_NEEDED` fields in the full JAR?

**Comment by randomstuff** [comment]
Cannot reproduce this issue anymore.

**Comment by randomstuff** [comment]
It seems to work fine with my Debian testing. The same JAR on a Ubuntu 10.04 fails:

* loading `libsimgrid.so` works fine;
* it fails when trying to load `libsimgrid-java.so` which depends on `libsimgrid.so` because it thinks `libsimgrid.so` is not loaded yet because we have loaded a copy in `/tmp/whatever`.

**Comment by randomstuff** [comment]
I'm going to check if this might be related to a change/difference of behaviour in `ld.so`.

**Comment by randomstuff** [comment]
Installed Ubuntu 10.04 on a VM and ran the same JAR file: it's working fine:

 * `Linux ubuntu 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
* OpenJDK 8u45-b14-1 (from Ubuntu).
* libc 2.21-0ubuntu4

**Comment by mquinson** [comment]
And what about a recent ubuntu version? It seems related to the linker somehow, so 2010 is a bit outdated here, maybe.

**Comment by randomstuff** [comment]
Sorry, I meant 15.04 (the same one we observed the bug on today).

**Comment by mquinson** [comment]
Maybe we should strace the JVM on a faulty system?

**Comment by randomstuff** [comment]
We could try `LD_DEBUG=libs java ...` as well which might be clearer.

**Comment by randomstuff** [comment]
The issue was caused by the fact that another version of `libsimgrid.so` was found and loaded instead of the currect one;

* the libsimgrid-dev (3.133) and libsimgrid3.133 packages were installed (with `/usr/lib/x86_64/libsimgrid.so` linking to `/usr/lib/x86_64/libsimgrid.so.3.11`);
* the compiled Java version was `libsimgrid.so` with `SONAME` `libsimgrid.so.3.12`.

Sequence:

1. the Java code tries to load the `simgrid` native lib and finds `/usr/lib/x86_64/libsimgrid.so` i.e. `/usr/lib/x86_64/libsimgrid.so.3.11` instead of 3.12;
2. the Java code tries to load the `simgrid-java` lib, does not find it and extracts it from the JAR;
3. this `libsimgrid-java.so` needs (`DT_NEEDED`) `libsimgrid.so.3.12`;
4. the dynamic linker tries to load/locate `libsimgrid.so.3.12` but does not find it.

**Comment by randomstuff** [comment]
(Removing the debian package, fixes the bug.)

**Comment by mquinson** [comment]
So the bug is in NativeLib.java:

        public static void nativeInit(String name) {
                try {
                        /* prefer the version on disk, if existing */
                        System.loadLibrary(name);
                } catch (UnsatisfiedLinkError e) {
                        /* If not found, unpack the one bundled into the jar file and use it */
                        loadLib(name);
                }
        }

we should simply do the reverse: prefer the embedded version, and if not found go for the system one.
